fix: urls
Former-commit-id: 595a33721f1895d4e928cb5955a0298d79163c7e

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -11,5 +11,13 @@ else
     exit 1
 fi
 
+echo "Running unit tests..."
+if bun run test; then
+    echo "All tests passed."
+else
+    echo "Some tests failed. Please fix them before committing."
+    exit 1
+fi
+
 echo "Staging changes..."
 git add .
